### ISSUE TITLE
Cache Module Controller IoC exception when ChangeTracking is disabled

### ISSUE THREAD

**Issue by Elyseum** [VirtoCommerce/vc-module-cache#12]
(I know the vc-module-cache has been deprecated in v3, but logging this as a reference for anyone who finds this useful)

The CacheModuleController requires an IChangesTrackingService as a ctor parameter. This service is only registered when VirtoCommerce:Cache.ChangeTracking.Enabled is true (see vc-module-cache\VirtoCommerce.CacheModule.Web\Module.cs). So when disabled, it crashes the controller construction:

```
Resolution of the dependency failed, type = "VirtoCommerce.CacheModule.Web.Controllers.Api.CacheModuleController", name = "(none)".
Exception occurred while: while resolving.
Exception is: InvalidOperationException - The current type, VirtoCommerce.CacheModule.Data.Services.IChangesTrackingService, is an interface and cannot be constructed. Are you missing a type mapping?
-----------------------------------------------
At the time of the exception, the container was:

  Resolving VirtoCommerce.CacheModule.Web.Controllers.Api.CacheModuleController,(none)
  Resolving parameter "changesTrackingService" of constructor VirtoCommerce.CacheModule.Web.Controllers.Api.CacheModuleController(VirtoCommerce.CacheModule.Data.Services.IChangesTrackingService changesTrackingService, CacheManager.Core.ICacheManager`1[[System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]] cacheManager)
    Resolving VirtoCommerce.CacheModule.Data.Services.IChangesTrackingService,(none)
```

I fixed this by registering a NoopChangesTrackingService when change tracking is disabled to prevent this.

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-4478 has been created

**Comment by yecli** [comment]
Good idea, could you create a PR for this?

**Comment by OlegoO** [comment]
we decided to postpone its implementation as core functionality.
