### ISSUE TITLE
Create a lightweight NuGet package with ICacheManagerAdapter interface

### ISSUE THREAD

**Issue by artem-dudarev** [VirtoCommerce/vc-module-cache#9]
**Problem**
When I want to use CacheManagerAdaptor methods I have to add a dependency on VirtoCommerce.CacheModule.Data, which in turn adds many other dependencies.

**Proposal of changes**
Create ICacheManagerAdapter abstraction for this implementation and put it to a lightweight NuGet package VirtoCommerce.CacheModule.Core or even to VirtoCommerce.Platform.Core.

**Comment by tatarincev** [comment]
We need get rid of this module at all.

**Comment by tatarincev** [comment]
No longer relevant for the platform 3.0 version
